### ISSUE TITLE
Invalid certificate (How?)

### ISSUE THREAD

**Issue by Syntheatizer** [ircd-hybrid/ircd-hybrid#13]
While starting irc-hybrid 8.2.21 I get this error:
[2018-11-19T18:48:29+0100] Could not set TLS keys -- Error in the certificate.
[2018-11-19T18:48:29+0100] Error while initializing TLS
Certificate chain file is made by:
cat server_certificate.crt > mycert.crt
cat ca_intermediate_certificate.crt >> mycert.crt
Details on how I've created the certificates and some crt generated:
https://paste.debian.net/hidden/74892ec1/
https://paste.debian.net/hidden/12e75da8/
Can I know what I'm doing wrong/what's the problem?

**Comment by miwob** [comment]
Technical support issue. Please seek for help on irc.ircd-hybrid.org if the issue persists.
