### ISSUE TITLE
nothing admin or op related works!

### ISSUE THREAD

**Issue by jamieduk** [ircd-hybrid/ircd-hybrid#15]
Why doint you get this all working and ready togo a user should just have to change paasword and username server name and url port etc and it all should work but i get error saying 

*OperServ* OPER ADMIN ADD R00T_UK
-
OperServ No such nick/channel
-
-> *OperServ* OPER ADMIN ADD *
-
OperServ No such nick/channel
-

**Comment by miwob** [comment]
Your report does not contain enough information. As such, we're unable to understand or reproduce the problem.
