### ISSUE TITLE
ircd-hybrid 8.2.26/28 mac osx build broken

### ISSUE THREAD

**Issue by chenrui333** [ircd-hybrid/ircd-hybrid#16]
relates https://github.com/Homebrew/homebrew-core/pull/48648 https://github.com/Homebrew/homebrew-core/pull/50182

I did tested locally against latest 8.2.30 on my catalina machine, receiving the same error:
```
==> /usr/local/Cellar/ircd-hybrid/8.2.30/bin/ircd -version
setrlimit: couldn't set maximum number of file descriptors: Invalid argument
```

**Comment by miwob** [comment]
Should be fixed now with f2428b2. Can you please check? I currently don't have macOS to run a test.

**Comment by chenrui333** [comment]
@miwob, sure I can pull a local build to verify the patch, thanks for the quick fix!

**Comment by chenrui333** [comment]
Yeah, just verified the patch, and submit a new PR, https://github.com/Homebrew/homebrew-core/pull/52307.

Thanks again!

**Comment by miwob** [comment]
You're welcome. Thanks for the report and testing!
