### ISSUE TITLE
Bug in channel mode +c

### ISSUE THREAD

**Issue by miragu** [ircd-hybrid/ircd-hybrid#19]
With the 8.2.30 tarball, channel mode +c is incorrectly matching accented characters as control chars. This comes down to a recent refactoring of msg_has_ctrls() that started doing numerical comparisons with signed chars. Attached patch simply reverts to the previous code with unsigned char.

[hybrid-8.2.30-mode-c-fix.txt](https://github.com/ircd-hybrid/ircd-hybrid/files/4542512/hybrid-8.2.30-mode-c-fix.txt)

**Comment by miwob** [comment]
Should be fixed now with 334ece4.
