### ISSUE TITLE
mkpasswd segfaults

### ISSUE THREAD

**Issue by falsovsky** [ircd-hybrid/ircd-hybrid#2]
Hi,

I've been doing some tests with mkpasswd on Linux and OpenBSD and it segfaults with various options.

I dont know if this is known. I will try to look more into it too.

| Cipher | Command | Linux | OpenBSD |
| --- | --- | --- | --- |
| Standard DES | ./mkpasswd -d -p morte | pIjVfxkVMQreQ | Segmentation fault (core dumped) |
| Standard DES + Salt | ./mkpasswd -d -s ab -p morte | abwavRK7NuFOo | Segmentation fault (core dumped) |
| Extended DES | ./mkpasswd -e -p morte | Segmentation fault (core dumped) | Segmentation fault (core dumped) |
| Extended DES + Salt | ./mkpasswd -e -s abcd -p morte | Segmentation fault (core dumped) | Segmentation fault (core dumped) |
| SHA-256 | ./mkpasswd -5 -p morte | $5$lch7iDnhO47X.DXQ$2Qghvgt2ebZZTwxdHAZh5H6kOUQANQANjv.h0Jm4si5 | Segmentation fault (core dumped) |
| SHA-256 + Salt | ./mkpasswd -5 -s abcd -p morte | $5$abcd$uiIwaqk4zcN4ioJhRkCiPVxrxbz8lsOjLBUFsBab8b3 | Segmentation fault (core dumped) |
| SHA-512 | ./mkpasswd -6 -p morte | $6$CUiXEy86IMErj25.$VRkAo7vGxnuAAIVFjm7AFr6ggBKgoQ8c/iv5UE5Ijf6mq1d/jsPkoU77ZhYXGNoCPphUDEvxTkys9YjQqNnYI/ | Segmentation fault (core dumped) |
| SHA-512 + Salt | ./mkpasswd -6 -s abcd -p morte | $6$abcd$sOnY5cdWF8Ph0unYaKH7lE4T6Ylu7JYpRPMByhq7LoTWHbypPLsl8wWyTYKjpmXn5WeAAZSJNJJHdxc54Iccx1 | Segmentation fault (core dumped) |
| MD5 | ./mkpasswd -m -p morte | $1$F95MCfa0$ubLw9e2/1H9u6e2rqioNK1 | Segmentation fault (core dumped) |
| MD5 + Salt | ./mkpasswd -m -s abcd -p morte | $1$abcd$xLdp7CoLasY75BtPPqxnm. | Segmentation fault (core dumped) |
| BlowFish | ./mkpasswd -b -p morte | Segmentation fault (core dumped) | $2a$04$QtRx7fCzjFPPpp8vo1I8X.l6P9Ja.CQC5OpBNYmVstZnMDrDh4g62 |
| BlowFish + Salt | ./mkpasswd -b -s abcd -p morte | Segmentation fault (core dumped) | : |
| Raw + Salt | ./mkpasswd -R abcd -p morte | abwavRK7NuFOo | Segmentation fault (core dumped) |

**Comment by miwob** [comment]
Thanks for spotting. This is because in the past it was usus that crypt() cannot fail. Nowadays some implementations return NULL. ircd related code has been updated for this case, but the mkpasswd tool hasn't. Should be fixed now.
