### ISSUE TITLE
Request: Configurable minimum TLS version

### ISSUE THREAD

**Issue by miragu** [ircd-hybrid/ircd-hybrid#20]
Over a year ago the minimum TLS version was hardcoded to 1.2. That's fine for maximum security but it would be nice to make it configurable. In my network I had to patch src/tls_openssl.c to get some old clients connecting again.
Thanks!

**Comment by miwob** [comment]
If you want to support a version below 1.2, you have to patch the sources yourself. Or have your users to update their clients instead. We're not adding support for something that's below 1.2, not even if it's configurable.
