### ISSUE TITLE
Ircd-hybrid with anope services

### ISSUE THREAD

**Issue by mayur3940** [ircd-hybrid/ircd-hybrid#23]
I have set both ircd.conf and services.conf file, but found issue that i cannot use /identify pass , always i have to identify my nick with /msg nickserv identify pass. Maybe pseudo not working with anope services.

**Comment by miwob** [comment]
Works fine here. Apparently your pseudo {} block isn't configured properly. Please get in touch with the community support if you need further assistance with this.

**Comment by mayur3940** [comment]
Now it's working fine, Thanks miwob
