### ISSUE TITLE
send.c change fails to compile

### ISSUE THREAD

**Issue by jeremyj84** [ircd-hybrid/ircd-hybrid#24]
It appears after a recent commit a buf to buffer change was missed on line 100 in src/send.c

send.c: In function 'send_message':
send.c:100:75: error: 'buf' undeclared (first use in this function)
  client_get_name(to, HIDE_IP), (dbuf_length(&to->connection->buf_sendq) + buf->size), get_sendq(&to->connection->confs));

**Comment by miwob** [comment]
The latest change to this were over 3 months ago. Our code looks correct and compiles with no issues since then. You might have messed up your tree somehow.
