### ISSUE TITLE
klugey logging (config vs stdout/stderr), no messages to stderr without use_logging

### ISSUE THREAD

**Issue by ghost** [ircd-hybrid/ircd-hybrid#25]
Just wanted to provide a little feedback on my experience, 

I had some syntax errors (which I'm still not really sure what they were so I just replaced the options with the example verbatim: 
xxx
But I was having trouble just getting to the point where I could even see the errors in the first place, eventually I settled for strace and I found that if I used the arg `ircd - logfile /dev/stdout` that it was sort of writing some of the messages and would stop when I eventually determined was because this was set to no: 

xxx
But I also had all sorts of other options in there for file logging that I stomped ultimately because this option `use_logging` is apparently mandatory to get any messages to stdout reliably. 

I wouldn't really ask for a testconf like ratbox as much as it would just be nice to have some messaging (that can be suppressed with -quiet if it has to be) but to stderr in which case I can redirect it to /dev/null if nothing else (that'd be fine.) but ideally irreversibly decoupled from any control logic in the config, I've tried doing that kind of stuff before and its just too confusing I think. 

doesn't need to be many messages, real basic startup messages to give me some hint that and leave the rest to use_logging. I don't really mind now that I understand sorta how it works, but there are people with little patience for which this would be a deal killer I think, their loss tbh but what a bummer if they couldn't even get past this. I'm pretty satisfied with the language of the configuration overall, still figuring this out though. I built up a network similar to this with RB once already in compose but I'm trying to be a bit neater this time around because I think I actually want to use hybrid so, unrelated note the one I setup with RB is on xxxx

It almost kinda seems like there should be a block there of some kind that groups items that probably shouldn't be different between servers like the nicklen but I don't know, the only place where I think it could possibly get out of hand in a way that isn't obvious is in the general block but nothing I couldn't figure out with diff if I had to.

**Comment by miwob** [comment]
Logging to standard streams isn't really supported. The main log file where important messages (including syntax errors) are logged to is the `ircd.log` file. Maybe in the future a test will be added to ensure only regular files are opened for logging.

Regarding the configuration directives like `max_nick_length`, etc.;  in ircd-hybrid there are no configuration directives that need to be the same on all servers. Limits apply to local clients only. Other servers may freely override this limit.
