### ISSUE TITLE
weird issue with +G for services?

### ISSUE THREAD

**Issue by ghost** [ircd-hybrid/ircd-hybrid#26]
I have OPERSERV setup to use +GR (soft caller-id and messages from private users only), +G being soft caller id should require that a user be in the same channel as OPERSERV to message it,  but it doesn't. I can message it with a regular registered nick even though we're not sharing any channels, however it does at least require you to me registered and identified to message it. I didn't know that one was supposed to negate the other though?

**Comment by miwob** [comment]
The caller id checking mechanism is performed by the server the target client is connected to. As OperServ is just a pseudo client which doesn't belong to a server that can perform this check, it can be messaged freely.

**Comment by ghost** [comment]
Gotcha, just FYI +D does work though and +G would be nice but I already gathered that it's somehow unrelated to the fact that +R works given that +D does work and that's fine, but I thought I might merely point out that ito an ordinary user it probably seems broken. So I won't be able to do it this way but I have another idea: 

- Botserv does have the ability to create aliases of itself 
- maybe possible to make operserv commands available (but only available) using a specific oper-only assignable alias as fantasy commands eg `fantasy { name = "KILL"; command = "operserv/kill"; }`
- assign the bot by specific alias to #oper  
- make operserv +g (or remove all commands from the operserv conf since they're not needed if +g isn't an option for the same reason) 
- Drop +D

So it seems like all I would have to do in this case is remove all of the command blocks from the operserv config, and try to add the fantasy module to operservconf and then set it up accordingly but I'll have to try, example
```
module
{
	name = "fantasy"
	#fantasycharacter = "!."
}
 command { service = "OperServ"; name = "SET FANTASY"; command = "operserv/set/fantasy"; }

fantasy { name = "AKILL"; command = "operserv/access"; }
fantasy { name = "CHANKILL"; command = "operserv/akick"; }
```
The only problem is I see with this is the default behavior (with OPERSERV assigned to a channel right now) is that it inherits all of the configuration from BOTSERV

**Comment by ghost** [comment]
Ok, so I found that I was able to switch to using fantasy commands for OPERSERV commands, and I can remove the privmsg commands from it entirely because no +g or +G even though +D works *shrugsies* and even though +R works which I assume is something that anope inherently respects. So there is absolutely no way to do this by running a single isolated instance of anope; 

- you can do it with two instances of anope I think where one has everything but operserv and the other has nothing but operserv and botserv (with botserv using a different service name) but both bots of this instance sharing the same redis database as the bots of the other instance. only goes to one channel (#oper) has no privmsg commands and only fantasy commands 

- service lines in hybrid config - can I use this to my advantage somehow? Could anything be considered advantageous at this point?

I think that will totally work however there's another problem I have with this which is that operserv apparently is not working correctly the oper command will add a user the user will appear to "be online using oper block" and it doesn't matter, it can't do anything, like the others which are "online using oper block" that are defined in the config. It's starting to piss me off now, so this seems like a good point to do what everybody else does and just give up on trying to have nice things. 

but for anybody interested here's the operserv config, the problem is these commands are not isolated then to only the operserv identity when its assigned to a channel (WHY ARE THESE EVEN ASSIGNABLE AT ALL... they really shouldn't be for that matter because its actually just botserv masquerading as whatever user when joined to any given channel :) but hence why two separate instances of anope such as described above may be an option 

```
/*
 * example configuration at https://github.com/anope/anope/blob/2.0/data/example.conf                         
 */

service
{
  nick                    = "OPERSERV"
  user                    = "OS"
  host                    = "operserv.host"
  gecos                   = "Operator Service"
  modes                   = "+Rop"
  channels                = "@#services,@#oper"
}

module
{
  name                    = "operserv"
  client                  = "OperServ"
  autokillexpiry          = 2d
  chankillexpiry          = 1d
  snlineexpiry            = 1d
  sqlineexpiry            = 1d
  akillonadd              = yes
  killonsnline            = yes
  killonsqline            = yes
  addakiller              = yes
  akillids                = yes
  opersonly               = no
}



module {
  name                    = "os_akill";
}

module {
  name                    = "os_config";
}

module {
  name                    = "os_chankill";
}

module {
  name                    = "os_forbid";
}

module {
  name                    = "os_ignore";
}

module {
  name                    = "os_info";
}

module {
  name                    = "os_jupe";
}

module {
  name                    = "os_kick";
}

module {
  name                    = "os_kill";
}

module {
  name                    = "os_list"
}

module {
  name                    = "os_mode";
}

module {
  name                    = "os_modinfo"
}

module
{
  name                    = "os_news"
  announcer               = "n00z3"
  oper_announcer          = "r00t"
}

module {
  name                    = "os_oper";
}

module {
  name                    = "os_reload";
}

module
{
  name                    = "os_set"
}

module {
  name                    = "os_shutdown"
}

module {
  name                    = "os_stats";
}

module {
  name                    = "os_svs"
}

module {
  name                    = "os_sxline";
}

module {
  name                    = "os_update";
}

fantasy {
  name                    = "AKILL";
  command                 = "operserv/akill";
  prepend_channel         = false;
  permission              = "operserv/akill";
}

fantasy {
  name                    = "CONFIG";
  command                 = "operserv/config";
  prepend_channel         = false;
  permission              = "operserv/config";
}


fantasy {
  name                    = "CHANKILL";
  command                 = "operserv/chankill";
  prepend_channel         = false;
  permission              = "operserv/chankill";
}

fantasy {
  name                    = "EXCEPTION";
  command                 = "operserv/exception";
  prepend_channel         = false;
  permission              = "operserv/exception";
}

fantasy {
  name                    = "FORBID";
  command                 = "operserv/forbid";
  prepend_channel         = false;
  permission              = "operserv/forbid";
}

fantasy {
  name                    = "JUPE";
  command                 = "operserv/jupe";
  prepend_channel         = false;
  permission              = "operserv/jupe";
}

fantasy {
  name                    = "KILL";
  command                 = "operserv/kill";
  prepend_channel         = false;
  permission              = "operserv/kill";
}

fantasy {
  name                    = "LOGONNEWS";
  command                 = "operserv/logonnews";
  prepend_channel         = false;
  permission              = "operserv/logonnews";
}

fantasy {
  name                    = "O_MODE";
  command                 = "operserv/mode";
  prepend_channel         = false;
  permission              = "operserv/mode";
}

fantasy {
  name                    = "NEWS";
  command                 = "operserv/news";
  prepend_channel         = false;
  permission              = "operserv/news";
}

fantasy {
  name                    = "OPER";
  command                 = "operserv/oper";
  prepend_channel         = false;
  permission              = "operserv/oper";
}

fantasy {
  name                    = "OPERNEWS";
  command                 = "operserv/opernews";
  prepend_channel         = false;
  permission              = "operserv/opernews";
}

fantasy {
  name                    = "RANDOMNEWS";
  command                 = "operserv/randomnews";
  prepend_channel         = false;
  permission              = "operserv/randomnews";
}

fantasy {
  name                    = "RELOAD";
  command                 = "operserv/reload";
  prepend_channel         = false;
  permission              = "operserv/reload";
}

fantasy {
  name                    = "SET";
  command                 = "operserv/set";
  prepend_channel         = false;
  permission              = "operserv/set";
}

fantasy {
  name                    = "SNLINE";
  command                 = "operserv/snline";
  prepend_channel         = false;
  permission              = "operserv/snline";
}

fantasy {
  name                    = "SQLINE";
  command                 = "operserv/sqline";
  prepend_channel         = false;
  permission              = "operserv/sqline";
}

fantasy {
  name                    = "SVSJOIN";
  command                 = "operserv/svsjoin";
  prepend_channel         = false;
  permission              = "operserv/svsjoin";
}

fantasy {
  name                    = "SVSNICK";
  command                 = "operserv/svsnick";
  prepend_channel         = false;
  permission              = "operserv/svsnick";
}

fantasy {
  name                    = "SVSPART";
  command                 = "operserv/svspart";
  prepend_channel         = false;
  permission              = "operserv/svspart";
}

fantasy {
  name                    = "UMODE";
  command                 = "operserv/umode";
  prepend_channel         = false;
  permission              = "operserv/umode";
}

fantasy {
  name                    = "UPDATE";
  command                 = "operserv/update";
  prepend_channel         = false;
  permission              = "operserv/update";
}

fantasy {
  name                    = "USERLIST";
  command                 = "operserv/userlist";
  prepend_channel         = false;
  permission              = "operserv/userlist";
}
```
