### ISSUE TITLE
Username with "-" not allowed?

### ISSUE THREAD

**Issue by c0dev0id** [ircd-hybrid/ircd-hybrid#32]
Hello,

We have a user who was able to log on to my ircd-hybrid instance with the following username in version 8.2.38:
tinfoil-hat [~tinfoil-h@161.97.xxx.xxx]

Now, in version 8.2.39, this is not allowed anymore. Removing the "-" fixes the username.

```
Connected. Now logging in.
* *** Looking up your hostname
* *** Found your hostname
* Capabilities supported: account-notify away-notify cap-notify chghost extended-join invite-notify multi-prefix userhost-in-names
* Capabilities requested: account-notify away-notify cap-notify chghost extended-join multi-prefix userhost-in-names 
* Capabilities acknowledged: account-notify away-notify cap-notify chghost extended-join multi-prefix userhost-in-names
* Closing Link: p5b151xxx.dip0.t-ipconnect.de (Invalid username [~tinfoil-h])
* Disconnected (Remote host closed socket)
```

I see the username validation has changed in 8.2.38 - there it worked. But not in 8.2.39.
Is this a bug or a feature? ;)

**Comment by miwob** [comment]
Depends on what `general::specials_in_ident` is set to. As you might have noticed in the changelog / NEWS file, the `dots_in_ident` directive has been renamed to `specials_in_ident` and now covers the `_`, and `-` characters in addition to `.`.

**Comment by c0dev0id** [comment]
@miwob: Ohhh! Excellent. I did not fully understand this part because I was not aware that the ident is actually the username.
Thanks for clarifying. I set `specials_in_ident = 2;` and it works now.
