### ISSUE TITLE
Call to freeaddrinfo() even when getaddrinfo() fails

### ISSUE THREAD

**Issue by sndrsmnk** [ircd-hybrid/ircd-hybrid#36]
Hi,

During some debugging i found that in [m_nick.c#L370](https://github.com/ircd-hybrid/ircd-hybrid/blob/8.2.x/modules/core/m_nick.c#L370) there could be a situation where getaddrinfo() fails and the code will still call freeaddrinfo() on the res ptr which might then be uninitialized and will cause general protection faults / segmentation faults.

Minor issue. That situation shouldn't really present itself i guess.
One fix _might_ be to set the res ptr to NULL instead of leaving it uninitialized.

Thanks for ircd-hybrid!

**Comment by miwob** [comment]
Fixed in bdc674e. Thanks!
