### ISSUE TITLE
Upgrade from 8.0.6

### ISSUE THREAD

**Issue by fgeek** [ircd-hybrid/ircd-hybrid#41]
Hello,

I have a network of two servers running 8.0.6. What is the recommended way to upgrade to latest 8.2.43 version?

I am getting error "Non-TS server" when servers are trying to link. I don't completely understand how include/server.h TS_CURRENT and TS_MINIMUM work.

I tried sending email to https://www.ircd-hybrid.org/support.html list, which does not seem to work and connecting to irc-server just says "Connection refused" (port is not open).

**Comment by Adam-** [comment]
It looks like the linking protocol was changed to deviate from TS6 at some point. If you update to 8.2.37 first and then 8.2.43 it will work I think. https://github.com/ircd-hybrid/ircd-hybrid/commit/3a232b1bc20ddc04301be5f3fa841e0daec4ef30

**Comment by fgeek** [comment]
Thanks. I will try that.
