### ISSUE TITLE
Errors while loading modules are ignored

### ISSUE THREAD

**Issue by progval** [ircd-hybrid/ircd-hybrid#47]
For example, if I put this in my config file:

```
module_base_path = "../lib/ircd-hybrid/modules";
```

and start hybrid, then `Loading module m_xline.la from: ../lib/ircd-hybrid/modules` etc is printed and no error is logged.

However, the module actually failed to load with this error: `Error loading module m_xline.la from: ../lib/ircd-hybrid/modules during exit: Module path ../lib/ircd-hybrid/modules/m_xline.la contains illegal directory traversal`

But this is silenced by `terminate` being `false` here:

https://github.com/ircd-hybrid/ircd-hybrid/blob/ca819db588de6c82257e37ad80afe57de72401ff/libio/src/module.c#L263-L279

**Comment by miwob** [comment]
Holla! Thanks for pointing this out, but these are basically just debugging notices, and the error/logging code is still a work in progress.
