### ISSUE TITLE
Consider adding support for IP address cloaking

### ISSUE THREAD

**Issue by ghost** [ircd-hybrid/ircd-hybrid#5]
Is it possible to optionally support IP address cloaking via a user mode (+x)?

There was once a patch to add IP address cloaking support to Hybrid, however it seems that patch is now many years old so does not work on the later releases.

It would be good to get this in Hybrid, even if it is optional during build time or something.

**Comment by miwob** [comment]
I'm yet to see a clean and secure implementation that covers both IPV4 and IPv6 support. So for now, this is not planned yet.

**Comment by ghost** [comment]
This might even be a good feature for anope anyway since it already supports hostserv/cloaking: https://github.com/anope/anope/blob/2.0/src/users.cpp#L211 

the only difference being that it needs to modify the user's hostmask on mode changes if the mode changed is +/-x. It dawned on me awhile ago that the code for hybrid is missing a lot of stuff that is common place in a lot of ircd's and to some extent I like it for that reason, I use services almost exclusively on my network to accomplish a lot of stuff, anope is missing a lot though.
