### ISSUE TITLE
Use OpenSSL for hashing passwords

### ISSUE THREAD

**Issue by falsovsky** [ircd-hybrid/ircd-hybrid#6]
Hi there!

The way mkpasswd now works (using crypt() ) makes it impossible to connect servers between Linux and BSD using crypted passwords.

Linux doesnt support blowfish, and BSD only suports blowfish.

Maybe it would be better to create the hashes using OpenSSL functions, as it would be more portable.

What do you think of this ? I can try to look first into mkpasswd. And then it also has to be changed in the ircd source.

**Comment by miwob** [comment]
The underlying implementation of crypt(3) isn't even remotely related to server-linking as passwords are always sent in plaintext over the wire, also this does of course does not prevent you from linking GNU/Linux and *BSD server.

**Comment by falsovsky** [comment]
So what does the "encrypted" option does in server linking?

This: https://github.com/ircd-hybrid/ircd-hybrid/blob/master/doc/reference.conf#L636
