### ISSUE TITLE
Consider adding nickserv re-authentication

### ISSUE THREAD

**Issue by codemonkeyrawks** [ircd-hybrid/ircd-hybrid#7]
When changing nicks (/msg nickserv <nick>) it would be nice if the server would send back a packet to the irc client allowing it to reauthenticate against set password and mark the new nick +R. It helps it so that I don't have to enter (/msg nickserv identify <password> each time when switching nicks.

**Comment by DanielOaks** [comment]
This would probably be something done with SASL authentication/reauth and/or its' numerics, I'm guessing? (and having the client reauth on its' own based on that). Seems like using those existing ones rather than creating new numerics makes sense.

**Comment by codemonkeyrawks** [comment]
Actually after looking at one of the irc networks I use (Geekshed - uses Unreal) it just uses the server for marking +r. It would be cool if on nick change it could look up the grouped nicks (slave and enslave) and mark the changed nick to +r (registered).

**Comment by Adam-** [comment]
This has nothing to do with the ircd.
