### ISSUE TITLE
Should there be an error message in foreground mode?

### ISSUE THREAD

**Issue by kkirsche** [ircd-hybrid/ircd-hybrid#9]
Good morning,

I'm working on building an IRC server (admittedly in a Docker container, commands to build are shown in: https://github.com/kkirsche/hybridirc-docker/blob/master/Dockerfile

After building it though, it appears to start, but then when I look at the process tree, it seems it's stopped / died, though without any error message. Is there any troubleshooting I can do to determine what's going wrong?

```
ircd@ba06240f3618:/$ /home/ircd/hybrid/bin/ircd -foreground -configfile /home/ircd/hybrid/etc/ircd.conf
ircd: version hybrid-8.2.19(20160821_7688)
ircd: pid 26
ircd: running in foreground mode from /home/ircd/hybrid
ircd@ba06240f3618:/$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 12:28 ?        00:00:00 /bin/bash
root        18     1  0 12:29 ?        00:00:00 su ircd
ircd        19    18  0 12:29 ?        00:00:00 bash
ircd        27    19  0 12:29 ?        00:00:00 ps -ef
```

**Comment by Adam-** [comment]
You can check the logfile. This isn't the place for support, use irc.ircd-hybrid.com#ircd-coders instead.

**Comment by kkirsche** [comment]
You could argue that lack of information to stdout and needing a log file is a bug, but I understand your point.

**Comment by kkirsche** [comment]
Thank you, this solved what I needed. I appreciate your patience.
